---
- name: Exclusão de arquivos .old 
  file: 
    state: absent
    path: "{{ jboss.path }}/server/{{ item.systempath }}/{{ item.artefact }}.old" 
  with_items: 
    - { 
        systempath: '{{ jboss.system.adm.path }}',
        artefact: '{{ jboss.system.adm.artefact.name }}'  
      }
    - { 
        systempath: '{{ jboss.system.venta.path }}',
        artefact: '{{ jboss.system.venta.artefact.name }}'  
      }
    - {
        systempath: '{{ jboss.system.client.path }}',
        artefact: '{{ jboss.system.client.artefact.name }}'  
      }

- name: Geração de backup para a versão atual
  copy:
    remote_src: True
    src: "{{ artefact.path }}/{{ item.job }}/{{ item.artefact }}"
    dest: "{{ jboss.path }}/server/{{ item.systempath }}/{{ item.artefact }}.old"
  with_items: 
    - { 
        systempath: '{{ jboss.system.adm.path }}',
        job:        '{{ jboss.system.adm.artefact.job }}',
        artefact: '{{ jboss.system.adm.artefact.name }}'  

      }
    - { 
        systempath: '{{ jboss.system.venta.path }}',
        job:        '{{ jboss.system.venta.artefact.job }}',
        artefact: '{{ jboss.system.venta.artefact.name }}'  
      }
    - {
        systempath: '{{ jboss.system.client.path }}',
        job:        '{{ jboss.system.client.artefact.job }}',
        artefact: '{{ jboss.system.client.artefact.name }}'  
      }  

- name: Exclusão da versão atual
  file: 
    state: absent
    path: "{{ jboss.path }}/server/{{ item.systempath }}/{{ item.artefact }}" 
  with_items: 
    - { 
        systempath: '{{ jboss.system.adm.path }}',
        artefact: '{{ jboss.system.adm.artefact.name }}'  
      }
    - { 
        systempath: '{{ jboss.system.venta.path }}',
        artefact: '{{ jboss.system.venta.artefact.name }}'  
      }
    - {
        systempath: '{{ jboss.system.client.path }}',
        artefact: '{{ jboss.system.client.artefact.name }}'  
      }
