---
# tasks file for jenkins

- name: Criação de pasta para o(s) artefato(s)
  file: path=/tmp/jobs/{{job}}

- name: download de artefatos
  get_url:
    url: http://{{address}}:{{port}}/job/{{system_adm}}/{{job}}/artifact/dist/{{item}}
    dest: /tmp/jobs/{{job}}/{{item}}
      with_items:
        - ventaboletosadm{{hostname}}.war
        - VentaBoletos{{hostname}}Prata.war
        - SCO_{{hostname}}.jar.pack.gz